### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by jasongaoks** [nothings/stb#56]
Hi!

I got some compile errors when I update stb_truetype.h to v1.01.
1.stb_truetype.h(2170) : warning C4013: 'assert' undefined; assuming extern returning int
  After replacing all the "assert" with "STBTT_assert", this warning disappered.
2.stb_truetype.h(2339) : error C2065: 'stbrp_coord' : undeclared identifier
  I thing this is because I don't have stb_rect_pack.h included in my application.
  Copy the typedef of 'stbrp_coord' from the stb_rect_pack.h can avoid this error.
